### ISSUE TITLE
Issue 18/05/2021

### ISSUE THREAD

**Issue by D0natellll0** [D0natellll0/wardikamal_2_22032021#2]
### TODO - Desk

- [ ]  Augmenter l'espacement en dessous des étoiles rating de la partie hébergement.
![Sans titre](https://user-images.githubusercontent.com/71557306/118642187-18baeb00-b7ec-11eb-94d7-b85d732677bb.png)

### TODO - Responsive

- [ ] Ajouter de l'espace vertical entre les "boutons" filtres.
![image](https://user-images.githubusercontent.com/71557306/118643210-4d7b7200-b7ed-11eb-947b-9ae2710a0812.png)

### Ce qui a été traité ce jour.

- [ ] correction syntaxe html `<img [...] >` en `<img [...] />`.
